spring:
  mail:
    host: smtp.qq.com #SMTP服务器地址
    username: 2569825222@qq.com #登陆账号
    password: ybcbhehwpyxgdjei #登陆密码（或授权码）
    properties:
      from:  2569825222@qq.com #邮件发信人（即真实邮箱）
  thymeleaf:
    cache: false
    prefix: classpath:/views/
  servlet:
    multipart:
      max-file-size: 10MB #限制单个文件大小
      max-request-size: 50MB #限制请求总量
